### ISSUE TITLE
Task got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by lem0nify** [awestlake87/pyo3-asyncio#19]
I'm trying to reproduce the simplest example with Python native module with async function exported and call it from Python.

**lib.rs:**
```Rust
use std::time::Duration;

use pyo3::{prelude::*, wrap_pyfunction};
use pyo3_asyncio::tokio::into_coroutine;

#[pyfunction]
fn foo(py: Python) -> PyResult<PyObject> {
    into_coroutine(py, async move {
        tokio::time::sleep(Duration::from_secs(1)).await;
        Python::with_gil(|py: Python| Ok(py.None()))
    })
}

#[pymodule]
fn simplelib(py: Python, m: &PyModule) -> PyResult<()> {
    pyo3_asyncio::try_init(py)?;
    pyo3_asyncio::tokio::init_multi_thread_once();
    m.add_function(wrap_pyfunction!(foo, m)?)?;
    Ok(())
}
```

**run.py:**
```Python
import asyncio
from simplelib import foo

async def main():
    await foo()

asyncio.run(main())
```

and it raises following error:
```
Traceback (most recent call last):
  File "C:\Users\l3m0n\code\py\simpleexaple\run.py", line 7, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\l3m0n\code\py\simpleexaple\run.py", line 5, in main
    await foo()
RuntimeError: Task <Task pending name='Task-1' coro=<main() running at C:\Users\l3m0n\code\py\simpleexaple\run.py:5> cb=[_run_until_complete_cb() at C:\Program Files\Python39\lib\asyncio\base_events.py:184]> got Future <Future pending> attached to a different loop
```

What's the problem?

My Cargo.toml:
```TOML
[package]
name = "simpleexaple"
version = "0.1.0"
edition = "2018"

[lib]
name = "simplelib"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
[dependencies.pyo3-asyncio]
version = "0.13.3"
features = ["tokio-runtime"]
[dependencies.tokio]
version = "1.6.0"
features = ["rt", "time"]
```

My Python version is: 3.9.5

**Comment by awestlake87** [comment]
`asyncio.run` is doing something very similar to `pyo3_asyncio::try_init` in that it sets up the asyncio event loop and manages the lifecycle. So what's happening here is that `simplelib` will set up its `pyo3_asyncio` event loop when it is imported, then `asyncio.run` sets up another event loop and runs the coroutine on that one instead. 

The error you see is saying that the `main()` coroutine is running on the event loop started by `asyncio.run`, but it is trying to await a future on the event loop created by `pyo3_asyncio`. Python apparently doesn't like it when these two event loops mix.

### Solution 1
Change the entrypoint to use the same event loop as `pyo3_asyncio` (which is obtained via `asyncio.get_event_loop()`):

```python
# current
asyncio.run(main())
```
```python
# fixed
asyncio.get_event_loop().run_until_complete(main())
```

### Solution 2
Make `pyo3_asyncio`'s initialization more flexible. Currently, we rely on `try_init` to configure all the python bits, which works well enough for applications. However, libraries don't have much control over how their application's `asyncio` loops are configured, so  `pyo3-asyncio` probably needs a more flexible initialization approach after all. 

I was thinking about ironing out some of the initialization concerns in release `0.14`, but if solution 1 doesn't work for you, then I can start addressing that sooner rather than later.

**Comment by awestlake87** [comment]
Also, this repo doesn't have any examples for writing native modules, so that's also something that I'll try to put together soon. Sorry the docs weren't much help this time!

**Comment by lem0nify** [comment]
> but if solution 1 doesn't work for you, then I can start addressing that sooner rather than later

No problem, it works. Thank you!

> Also, this repo doesn't have any examples for writing native modules, so that's also something that I'll try to put together soon. Sorry the docs weren't much help this time!

Yes, it is a problem. I've googled and tried to find something in docs for a few hours but your solution was something new to me.

**Comment by awestlake87** [comment]
Awesome, I'm glad that's working for you! I'll try to add some sort of native module example to the README sometime this week.

**Comment by awestlake87** [comment]
I uploaded some docs for native modules. It's basically what you've already done, but if there's anything else I should add to them, feel free to make some suggestions!

**Comment by normanrz** [comment]
Hi, I ran into a similar problem. I am trying to build a rust module that crunches some data for a `aiohttp`/`sanic` server. It would be fantastic, if the rust module could re-use that event loop.
For now, I was able to re-use the rust modules's event loop for the server (by exposing the `get_event_loop` function), but that seems like a suboptimal solution.

**Comment by awestlake87** [comment]
What do you mean by reuse the event loop? Were you trying to get a reference to it from python or attempting to use it after it had been shutdown?

**Comment by normanrz** [comment]
I got a reference to the event loop to use in in Python to simultaneously share the event loop between rust module and Python server.

**Comment by awestlake87** [comment]
`pyo3-asyncio` uses the standard [`asyncio.get_event_loop()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop) function to get a reference to the event loop during initialization. If you call that function in Python, it should return the same reference as `pyo3_asyncio::get_event_loop()`. Does that function work for your use-case?

**Comment by normanrz** [comment]
That is good to know! I dug into the sanic code understand my problem better: Upon startup, the server creates a new event loop and sets it as the new default asyncio loop. It does so, because sanic has multiprocessing capabilities (not 100% sure why that is necessary). However, at that point, the rust module has already been initialised with the previous default event loop. I can create the server in a way to use the default asyncio loop. It is a bit verbose (which is an issue on the sanic side), but solves my problem.

**Comment by awestlake87** [comment]
Hmm, that is a bit tricky. As an alternative, if it makes things cleaner, you could try to move the call to `pyo3_asyncio::try_init()` after the new event loop has been set up. I've been recommending people call that fn in the module import, but that might not be the best place for you to call it in this case.

I'll mark that down as an issue for initialization. It seems like the current setup can cause some problems, so there's probably a better solution that can be rolled out in 0.14

**Comment by Bengreen** [comment]
I tried a simple pytest example

```python
from setuptools_rust_starter import sleep_for, foo
import asyncio

async def test_python_sleep(loop):
    await asyncio.sleep(1)

async def test_rust_sleep_foo(loop):
    await foo()
```

which results in this error
```
loop = <_UnixSelectorEventLoop running=False closed=False debug=False>

    async def test_rust_sleep_foo(loop):
>       await foo()
E       RuntimeError: Task <Task pending name='Task-2' coro=<test_rust_sleep_foo() running at /Users/ben.greene/Development/Personal/rusty-python/tests/test_asyncio.py:9> cb=[_run_until_complete_cb() at /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending> attached to a different loop

tests/test_asyncio.py:9: RuntimeError```

I believe that pytest will create a new clean loop for each test ... So I would guess that grabbing the event loop during init/import would not work as the event loop would not exist at that time. So how to code the function to get the correct event loop?

**Comment by Bengreen** [comment]
What is pythons expectation in terms of event loops.

Is it expected that the event loop is identified as the active event loop when the async function call is made ?
Would that make the identification of event loop during initialisation potentially incorrect?

**Comment by Bengreen** [comment]
I see #30 seems to address some items in this thread?

**Comment by awestlake87** [comment]
You're right, @Bengreen. This kind of problem is what #30 is meant to solve since the `0.13` API always caches the first call to `get_event_loop` and treats it as the applications sole event loop. This turned out to be a mistake that caused a lot of headaches in the first release.

The documentation is still in-progress, but the functionality should all be there if you want to try it out. Essentially anything on the [init-fixes](https://github.com/awestlake87/pyo3-asyncio/tree/init-fixes) branch that's not marked as deprecated will always get the current event loop instead of the cached event loop.

I'm aiming for releasing it within a week or two, but if you're willing to put up with some missing docs it'd be nice to have someone else try it out beforehand in case there are problems we missed. Feel free to comment and ask questions on that PR as well!
